version: 0.2

# AWS CodeBuild Specification for Mini-XDR Backend
# Builds Docker image and pushes to ECR

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    AWS_ACCOUNT_ID: "116912495274"
    ECR_REPOSITORY: mini-xdr-backend
  parameter-store:
    # Optional: Store sensitive build args in Parameter Store
    # JWT_SECRET_KEY: /mini-xdr/jwt-secret

phases:
  pre_build:
    commands:
      - echo "=== Pre-Build Phase ==="
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      # Extract version from git tag if available
      - |
        if [ ! -z "$CODEBUILD_WEBHOOK_TRIGGER" ]; then
          if [[ "$CODEBUILD_WEBHOOK_TRIGGER" == tag/* ]]; then
            VERSION_TAG=$(echo $CODEBUILD_WEBHOOK_TRIGGER | sed 's/tag\///')
            VERSION_NUMBER=$(echo $VERSION_TAG | sed 's/v//')
            echo "Building from webhook tag: $VERSION_TAG (version: $VERSION_NUMBER)"
          fi
        else
          # Fallback: Check for git tags on current commit
          git fetch --tags 2>/dev/null || true
          VERSION_TAG=$(git describe --exact-match --tags HEAD 2>/dev/null || echo "")
          if [ ! -z "$VERSION_TAG" ]; then
            VERSION_NUMBER=$(echo $VERSION_TAG | sed 's/v//')
            echo "Building from git tag: $VERSION_TAG (version: $VERSION_NUMBER)"
          fi
        fi
      - echo "Repository URI: $REPOSITORY_URI"
      - echo "Image Tag: $IMAGE_TAG"
      - echo "Build started on $(date)"

  build:
    commands:
      - echo "=== Build Phase ==="
      - echo "Building backend Docker image..."
      - cd backend
      - |
        if [ ! -z "$VERSION_NUMBER" ]; then
          # Build with version tags
          docker build \
            --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
            --build-arg VCS_REF="$COMMIT_HASH" \
            --build-arg VERSION="$VERSION_NUMBER" \
            -t $REPOSITORY_URI:$VERSION_NUMBER \
            -t $REPOSITORY_URI:$IMAGE_TAG \
            -t $REPOSITORY_URI:latest \
            .
        else
          # Build with commit hash only
          docker build \
            --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
            --build-arg VCS_REF="$COMMIT_HASH" \
            -t $REPOSITORY_URI:$IMAGE_TAG \
            -t $REPOSITORY_URI:latest \
            .
        fi
      - echo "Backend image built successfully"

  post_build:
    commands:
      - echo "=== Post-Build Phase ==="
      - echo "Build completed on $(date)"
      - echo "Pushing Docker images to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - |
        if [ ! -z "$VERSION_NUMBER" ]; then
          docker push $REPOSITORY_URI:$VERSION_NUMBER
          echo "Pushed version tag: $VERSION_NUMBER"
        fi
      - echo "Writing image definitions file..."
      - printf '[{"name":"backend","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > ../imagedefinitions-backend.json
      - echo "Backend build and push complete!"

artifacts:
  files:
    - imagedefinitions-backend.json
  name: backend-build-artifacts

cache:
  paths:
    - '/root/.cache/pip/**/*'
    - 'backend/venv/**/*'
