"use client";

import React, { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Checkbox } from "@/components/ui/checkbox";
import { Shield, Play, Loader2, CheckCircle, XCircle } from "lucide-react";
import type { IncidentCoordination } from "@/lib/agent-api";
import { apiUrl } from "@/app/utils/api";

interface ResponseActionsTabProps {
  incident: any;
  coordination: IncidentCoordination | null;
}

export function ResponseActionsTab({ incident, coordination }: ResponseActionsTabProps) {
  const [executing, setExecuting] = useState<string | null>(null);

  const containment = coordination?.agent_decisions?.containment;
  const recommendedActions = coordination?.recommendations || [];

  const handleExecute = async (action: string) => {
    setExecuting(action);
    try {
      // In a real implementation, this would call the backend
      await new Promise(resolve => setTimeout(resolve, 2000)); // Simulate delay
      alert(`Executed: ${action}`);
    } catch (e) {
      console.error(e);
    } finally {
      setExecuting(null);
    }
  };

  return (
    <div className="space-y-6">
       {/* Quick Actions */}
       <div className="flex gap-4 overflow-x-auto pb-2">
          <Button variant="destructive" className="gap-2" onClick={() => handleExecute("Isolate Host")}>
             <Shield className="h-4 w-4" /> Isolate Host
          </Button>
          <Button variant="outline" className="gap-2" onClick={() => handleExecute("Block IP")}>
             <Shield className="h-4 w-4" /> Block IP {incident.src_ip}
          </Button>
          <Button variant="outline" className="gap-2" onClick={() => handleExecute("Hunt Similar")}>
             <Search className="h-4 w-4" /> Hunt Similar
          </Button>
       </div>

       <div className="grid md:grid-cols-2 gap-6">
          {/* Automated Plan */}
          <Card>
             <CardHeader>
                <CardTitle className="flex items-center gap-2">
                    <Play className="h-5 w-5 text-blue-500" />
                    Automated Response Plan
                </CardTitle>
                <CardDescription>Generated by OpenAI & Containment Agent</CardDescription>
             </CardHeader>
             <CardContent>
                <div className="space-y-4">
                    {recommendedActions.map((action, idx) => (
                        <div key={idx} className="flex items-start gap-3 p-3 border rounded-lg hover:bg-muted/50">
                            <Checkbox id={`action-${idx}`} />
                            <div className="grid gap-1.5 leading-none">
                                <label
                                    htmlFor={`action-${idx}`}
                                    className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
                                >
                                    {action}
                                </label>
                                <p className="text-sm text-muted-foreground">
                                    Recommended by Agent Coordination Hub
                                </p>
                            </div>
                        </div>
                    ))}
                    {recommendedActions.length === 0 && (
                        <p className="text-muted-foreground text-sm">No automated actions proposed.</p>
                    )}
                    <Button className="w-full" disabled={recommendedActions.length === 0 || !!executing}>
                        {executing ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Play className="mr-2 h-4 w-4" />}
                        Execute Selected
                    </Button>
                </div>
             </CardContent>
          </Card>

          {/* Action History */}
          <Card>
             <CardHeader>
                <CardTitle>Action History</CardTitle>
             </CardHeader>
             <CardContent>
                <Table>
                    <TableHeader>
                        <TableRow>
                            <TableHead>Action</TableHead>
                            <TableHead>Status</TableHead>
                            <TableHead>Agent</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {containment?.actions_taken?.map((action: string, idx: number) => (
                            <TableRow key={idx}>
                                <TableCell className="font-medium text-xs">{action}</TableCell>
                                <TableCell>
                                    <Badge variant="outline" className="bg-green-500/10 text-green-500 border-green-500/20">
                                        Completed
                                    </Badge>
                                </TableCell>
                                <TableCell className="text-muted-foreground text-xs">Containment</TableCell>
                            </TableRow>
                        ))}
                        {(!containment?.actions_taken || containment.actions_taken.length === 0) && (
                            <TableRow>
                                <TableCell colSpan={3} className="text-center text-muted-foreground py-8">
                                    No actions taken yet
                                </TableCell>
                            </TableRow>
                        )}
                    </TableBody>
                </Table>
             </CardContent>
          </Card>
       </div>
    </div>
  );
}
