AWSTemplateFormatVersion: '2010-09-09'
Description: 'Mini-XDR Secure AWS Deployment - No hardcoded passwords or 0.0.0.0/0 exposures'

Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 Key Pair for SSH access
    
  YourPublicIP:
    Type: String
    Description: Your public IP address (from curl ipinfo.io/ip)
    AllowedPattern: '^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$'
    
  InstanceType:
    Type: String
    Default: t3.medium
    AllowedValues: [t3.micro, t3.small, t3.medium, t3.large]
    Description: EC2 instance type
    
  DatabasePassword:
    Type: String
    NoEcho: true
    MinLength: 12
    Description: Secure database password (min 12 chars)
    Default: "{{resolve:secretsmanager:mini-xdr/database-password:SecretString}}"

Resources:
  # VPC with proper network segmentation
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: mini-xdr-secure-vpc

  # Public subnet for backend (restricted access)
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: mini-xdr-public-subnet

  # Private subnet for database
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: mini-xdr-private-subnet

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: mini-xdr-igw

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Route table for public subnet
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: mini-xdr-public-rt

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # SECURE Security Group - NO 0.0.0.0/0 exposures
  BackendSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SECURE security group for Mini-XDR backend - NO open access
      VpcId: !Ref VPC
      SecurityGroupIngress:
        # SSH access ONLY from your IP
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${YourPublicIP}/32"
          Description: SSH access from admin IP only
        # API access ONLY from your IP
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: !Sub "${YourPublicIP}/32"
          Description: Mini-XDR API from admin IP only
        # TPOT honeypot access (specific IP only)
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 34.193.101.171/32
          Description: TPOT data ingestion
      Tags:
        - Key: Name
          Value: mini-xdr-secure-backend-sg

  # Database Security Group - PRIVATE access only
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SECURE database security group - backend access only
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref BackendSecurityGroup
          Description: PostgreSQL access from backend only
      Tags:
        - Key: Name
          Value: mini-xdr-secure-db-sg

  # Database Subnet Group
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Mini-XDR database
      SubnetIds:
        - !Ref PublicSubnet
        - !Ref PrivateSubnet
      Tags:
        - Key: Name
          Value: mini-xdr-db-subnet-group

  # SECURE RDS Database with encryption
  Database:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      DBInstanceIdentifier: mini-xdr-secure-db
      DBInstanceClass: db.t3.micro
      Engine: postgres
      EngineVersion: "15.4"
      MasterUsername: postgres
      MasterUserPassword: !Ref DatabasePassword
      AllocatedStorage: 20
      StorageType: gp2
      StorageEncrypted: true  # ENCRYPTION ENABLED
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      BackupRetentionPeriod: 7
      MultiAZ: false
      PubliclyAccessible: false  # PRIVATE DATABASE
      DeletionProtection: true   # DELETION PROTECTION
      Tags:
        - Key: Name
          Value: mini-xdr-secure-database

  # IAM Role with LEAST PRIVILEGE (no AmazonSageMakerFullAccess)
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SecureS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub "${ModelsBucket}/*"
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !GetAtt ModelsBucket.Arn
        - PolicyName: SecureSecretsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:mini-xdr/*"
        - PolicyName: SecureCloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/ec2/mini-xdr*"
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/ec2/mini-xdr*:*"

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  # SECURE S3 Bucket with encryption and access controls
  ModelsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "mini-xdr-models-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: mini-xdr-secure-models

  # CloudWatch Log Group for S3 access logging
  S3LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/s3/mini-xdr-access-logs
      RetentionInDays: 30

  # Backend EC2 Instance with secure configuration
  BackendInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Sub "{{resolve:ssm:/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id}}"
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref BackendSecurityGroup
      SubnetId: !Ref PublicSubnet
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -euo pipefail
          
          # Update system
          apt-get update -y
          apt-get upgrade -y
          
          # Install dependencies
          apt-get install -y python3 python3-pip python3-venv git curl wget htop vim \
                             awscli postgresql-client-15 build-essential libssl-dev
          
          # Create mini-xdr directory
          mkdir -p /opt/mini-xdr
          chown ubuntu:ubuntu /opt/mini-xdr
          
          # Generate secure API key and store in Secrets Manager
          SECURE_API_KEY=$(openssl rand -hex 32)
          aws secretsmanager create-secret \
            --name "mini-xdr/api-key" \
            --secret-string "$SECURE_API_KEY" \
            --region "${AWS::Region}" || \
          aws secretsmanager update-secret \
            --secret-id "mini-xdr/api-key" \
            --secret-string "$SECURE_API_KEY" \
            --region "${AWS::Region}"
          
          # Create secure environment file
          cat > /opt/mini-xdr/.env << 'ENVEOF'
          # SECURE Mini-XDR Configuration
          API_HOST=0.0.0.0
          API_PORT=8000
          UI_ORIGIN=http://localhost:3000,http://${YourPublicIP}:3000
          
          # Secure API key from Secrets Manager
          API_KEY=$(aws secretsmanager get-secret-value --secret-id mini-xdr/api-key --query SecretString --output text)
          
          # Secure database connection with SSL
          DATABASE_URL=postgresql://postgres:${DatabasePassword}@${Database.Endpoint.Address}:5432/postgres?sslmode=require
          
          # Detection Configuration
          FAIL_WINDOW_SECONDS=60
          FAIL_THRESHOLD=6
          AUTO_CONTAIN=false
          
          # Honeypot Configuration - TPOT (secure)
          HONEYPOT_HOST=34.193.101.171
          HONEYPOT_USER=admin
          HONEYPOT_SSH_KEY=/home/ubuntu/.ssh/mini-xdr-tpot-key.pem
          HONEYPOT_SSH_PORT=64295
          
          # LLM Configuration (secure - from Secrets Manager)
          LLM_PROVIDER=openai
          OPENAI_API_KEY=$(aws secretsmanager get-secret-value --secret-id mini-xdr/openai-api-key --query SecretString --output text 2>/dev/null || echo "NOT_CONFIGURED")
          OPENAI_MODEL=gpt-4o-mini
          
          # Optional: X.AI Configuration
          XAI_API_KEY=$(aws secretsmanager get-secret-value --secret-id mini-xdr/xai-api-key --query SecretString --output text 2>/dev/null || echo "NOT_CONFIGURED")
          XAI_MODEL=grok-beta
          
          # Threat Intelligence APIs (secure - from Secrets Manager)
          ABUSEIPDB_API_KEY=$(aws secretsmanager get-secret-value --secret-id mini-xdr/abuseipdb-api-key --query SecretString --output text 2>/dev/null || echo "NOT_CONFIGURED")
          VIRUSTOTAL_API_KEY=$(aws secretsmanager get-secret-value --secret-id mini-xdr/virustotal-api-key --query SecretString --output text 2>/dev/null || echo "NOT_CONFIGURED")
          
          # ML Models Path
          ML_MODELS_PATH=/opt/mini-xdr/models
          POLICIES_PATH=/opt/mini-xdr/policies
          
          # AWS Configuration
          MODELS_BUCKET=${ModelsBucket}
          AWS_REGION=${AWS::Region}
          ENVEOF
          
          chown ubuntu:ubuntu /opt/mini-xdr/.env
          chmod 600 /opt/mini-xdr/.env
          
          echo "Secure Mini-XDR setup completed!" > /var/log/mini-xdr-secure-setup.log

      Tags:
        - Key: Name
          Value: mini-xdr-secure-backend

  # Elastic IP for consistent addressing
  BackendEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref BackendInstance
      Tags:
        - Key: Name
          Value: mini-xdr-secure-eip

Outputs:
  BackendPublicIP:
    Description: Public IP of the Mini-XDR backend
    Value: !Ref BackendEIP
    Export:
      Name: !Sub "${AWS::StackName}-PublicIP"
      
  BackendInstanceId:
    Description: Instance ID of the Mini-XDR backend
    Value: !Ref BackendInstance
    Export:
      Name: !Sub "${AWS::StackName}-InstanceId"
      
  DatabaseEndpoint:
    Description: RDS database endpoint
    Value: !GetAtt Database.Endpoint.Address
    Export:
      Name: !Sub "${AWS::StackName}-DatabaseEndpoint"
      
  ModelsBucket:
    Description: S3 bucket for ML models
    Value: !Ref ModelsBucket
    Export:
      Name: !Sub "${AWS::StackName}-ModelsBucket"
      
  SSHCommand:
    Description: Secure SSH command to connect to backend
    Value: !Sub "ssh -i ~/.ssh/${KeyPairName}.pem ubuntu@${BackendEIP}"
    
  APIEndpoint:
    Description: Mini-XDR API endpoint (restricted to your IP)
    Value: !Sub "http://${BackendEIP}:8000"

  SecurityStatus:
    Description: Security posture of this deployment
    Value: "SECURE - No 0.0.0.0/0 exposures, encrypted database, least-privilege IAM"
