"""Initial database schema

Revision ID: 0502143bdcb1
Revises: 
Create Date: 2025-09-27 21:57:18.920024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0502143bdcb1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_playbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('average_execution_time', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('compliance_frameworks', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_playbooks_category'), 'response_playbooks', ['category'], unique=False)
    op.create_index(op.f('ix_response_playbooks_created_at'), 'response_playbooks', ['created_at'], unique=False)
    op.create_index(op.f('ix_response_playbooks_name'), 'response_playbooks', ['name'], unique=True)
    op.create_index(op.f('ix_response_playbooks_status'), 'response_playbooks', ['status'], unique=False)
    op.create_table('response_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workflow_id', sa.String(length=64), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('playbook_name', sa.String(length=128), nullable=True),
    sa.Column('playbook_version', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('execution_log', sa.JSON(), nullable=True),
    sa.Column('current_step_data', sa.JSON(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('auto_executed', sa.Boolean(), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_rollback_enabled', sa.Boolean(), nullable=True),
    sa.Column('rollback_plan', sa.JSON(), nullable=True),
    sa.Column('rollback_executed', sa.Boolean(), nullable=True),
    sa.Column('rollback_reason', sa.String(length=256), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_workflows_created_at'), 'response_workflows', ['created_at'], unique=False)
    op.create_index(op.f('ix_response_workflows_incident_id'), 'response_workflows', ['incident_id'], unique=False)
    op.create_index(op.f('ix_response_workflows_playbook_name'), 'response_workflows', ['playbook_name'], unique=False)
    op.create_index(op.f('ix_response_workflows_status'), 'response_workflows', ['status'], unique=False)
    op.create_index(op.f('ix_response_workflows_workflow_id'), 'response_workflows', ['workflow_id'], unique=True)
    op.create_table('advanced_response_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_id', sa.String(length=64), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('parent_action_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=True),
    sa.Column('action_category', sa.String(length=32), nullable=True),
    sa.Column('action_name', sa.String(length=128), nullable=True),
    sa.Column('action_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('safety_checks', sa.JSON(), nullable=True),
    sa.Column('impact_assessment', sa.JSON(), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rollback_action_id', sa.Integer(), nullable=True),
    sa.Column('rollback_data', sa.JSON(), nullable=True),
    sa.Column('rollback_executed', sa.Boolean(), nullable=True),
    sa.Column('executed_by', sa.String(length=64), nullable=True),
    sa.Column('execution_method', sa.String(length=32), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['parent_action_id'], ['advanced_response_actions.id'], ),
    sa.ForeignKeyConstraint(['rollback_action_id'], ['advanced_response_actions.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['response_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advanced_response_actions_action_category'), 'advanced_response_actions', ['action_category'], unique=False)
    op.create_index(op.f('ix_advanced_response_actions_action_id'), 'advanced_response_actions', ['action_id'], unique=True)
    op.create_index(op.f('ix_advanced_response_actions_action_type'), 'advanced_response_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_advanced_response_actions_created_at'), 'advanced_response_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_advanced_response_actions_incident_id'), 'advanced_response_actions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_advanced_response_actions_status'), 'advanced_response_actions', ['status'], unique=False)
    op.create_index(op.f('ix_advanced_response_actions_workflow_id'), 'advanced_response_actions', ['workflow_id'], unique=False)
    op.create_table('response_impact_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('attacks_blocked', sa.Integer(), nullable=True),
    sa.Column('false_positives', sa.Integer(), nullable=True),
    sa.Column('systems_affected', sa.Integer(), nullable=True),
    sa.Column('users_affected', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('downtime_minutes', sa.Integer(), nullable=True),
    sa.Column('cost_impact_usd', sa.Float(), nullable=True),
    sa.Column('compliance_impact', sa.String(length=32), nullable=True),
    sa.Column('metrics_data', sa.JSON(), nullable=True),
    sa.Column('external_metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['response_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_impact_metrics_created_at'), 'response_impact_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_response_impact_metrics_workflow_id'), 'response_impact_metrics', ['workflow_id'], unique=False)
    op.create_table('response_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=True),
    sa.Column('approval_type', sa.String(length=32), nullable=True),
    sa.Column('impact_level', sa.String(length=16), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emergency_override', sa.Boolean(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('override_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['advanced_response_actions.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['response_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_approvals_action_id'), 'response_approvals', ['action_id'], unique=False)
    op.create_index(op.f('ix_response_approvals_approval_type'), 'response_approvals', ['approval_type'], unique=False)
    op.create_index(op.f('ix_response_approvals_created_at'), 'response_approvals', ['created_at'], unique=False)
    op.create_index(op.f('ix_response_approvals_impact_level'), 'response_approvals', ['impact_level'], unique=False)
    op.create_index(op.f('ix_response_approvals_requested_by'), 'response_approvals', ['requested_by'], unique=False)
    op.create_index(op.f('ix_response_approvals_status'), 'response_approvals', ['status'], unique=False)
    op.create_index(op.f('ix_response_approvals_workflow_id'), 'response_approvals', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_approvals_workflow_id'), table_name='response_approvals')
    op.drop_index(op.f('ix_response_approvals_status'), table_name='response_approvals')
    op.drop_index(op.f('ix_response_approvals_requested_by'), table_name='response_approvals')
    op.drop_index(op.f('ix_response_approvals_impact_level'), table_name='response_approvals')
    op.drop_index(op.f('ix_response_approvals_created_at'), table_name='response_approvals')
    op.drop_index(op.f('ix_response_approvals_approval_type'), table_name='response_approvals')
    op.drop_index(op.f('ix_response_approvals_action_id'), table_name='response_approvals')
    op.drop_table('response_approvals')
    op.drop_index(op.f('ix_response_impact_metrics_workflow_id'), table_name='response_impact_metrics')
    op.drop_index(op.f('ix_response_impact_metrics_created_at'), table_name='response_impact_metrics')
    op.drop_table('response_impact_metrics')
    op.drop_index(op.f('ix_advanced_response_actions_workflow_id'), table_name='advanced_response_actions')
    op.drop_index(op.f('ix_advanced_response_actions_status'), table_name='advanced_response_actions')
    op.drop_index(op.f('ix_advanced_response_actions_incident_id'), table_name='advanced_response_actions')
    op.drop_index(op.f('ix_advanced_response_actions_created_at'), table_name='advanced_response_actions')
    op.drop_index(op.f('ix_advanced_response_actions_action_type'), table_name='advanced_response_actions')
    op.drop_index(op.f('ix_advanced_response_actions_action_id'), table_name='advanced_response_actions')
    op.drop_index(op.f('ix_advanced_response_actions_action_category'), table_name='advanced_response_actions')
    op.drop_table('advanced_response_actions')
    op.drop_index(op.f('ix_response_workflows_workflow_id'), table_name='response_workflows')
    op.drop_index(op.f('ix_response_workflows_status'), table_name='response_workflows')
    op.drop_index(op.f('ix_response_workflows_playbook_name'), table_name='response_workflows')
    op.drop_index(op.f('ix_response_workflows_incident_id'), table_name='response_workflows')
    op.drop_index(op.f('ix_response_workflows_created_at'), table_name='response_workflows')
    op.drop_table('response_workflows')
    op.drop_index(op.f('ix_response_playbooks_status'), table_name='response_playbooks')
    op.drop_index(op.f('ix_response_playbooks_name'), table_name='response_playbooks')
    op.drop_index(op.f('ix_response_playbooks_created_at'), table_name='response_playbooks')
    op.drop_index(op.f('ix_response_playbooks_category'), table_name='response_playbooks')
    op.drop_table('response_playbooks')
    # ### end Alembic commands ###
