"""Add triggering events fields to incidents

Revision ID: 191220d80f32
Revises: d9ea5c5841db
Create Date: 2025-11-23 01:44:05.740597

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "191220d80f32"
down_revision: Union[str, None] = "d9ea5c5841db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "action_logs",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "actions",
        "tpot_verification_timestamp",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.add_column(
        "cloud_assets",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
    )
    op.add_column(
        "cloud_assets", sa.Column("agent_enrollment_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "cloud_assets",
        sa.Column("deployment_method", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "cloud_assets", sa.Column("deployment_error", sa.Text(), nullable=True)
    )
    op.drop_index("idx_cloud_assets_org_provider", table_name="cloud_assets")
    op.drop_index("idx_cloud_assets_status", table_name="cloud_assets")
    op.drop_index("idx_cloud_assets_type", table_name="cloud_assets")
    op.drop_constraint(
        "uq_cloud_assets_org_provider_asset", "cloud_assets", type_="unique"
    )
    op.create_index(
        op.f("ix_cloud_assets_agent_deployed"),
        "cloud_assets",
        ["agent_deployed"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cloud_assets_agent_status"),
        "cloud_assets",
        ["agent_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cloud_assets_asset_id"), "cloud_assets", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_cloud_assets_asset_type"), "cloud_assets", ["asset_type"], unique=False
    )
    op.create_index(
        op.f("ix_cloud_assets_created_at"), "cloud_assets", ["created_at"], unique=False
    )
    op.create_index(
        "ix_cloud_assets_org_provider_asset",
        "cloud_assets",
        ["organization_id", "provider", "asset_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_cloud_assets_organization_id"),
        "cloud_assets",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cloud_assets_provider"), "cloud_assets", ["provider"], unique=False
    )
    op.create_foreign_key(
        None, "cloud_assets", "agent_enrollments", ["agent_enrollment_id"], ["id"]
    )
    op.create_index(
        op.f("ix_containment_policies_organization_id"),
        "containment_policies",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "containment_policies",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        "ix_events_org_ts", "events", ["organization_id", "ts"], unique=False
    )
    op.create_index(
        op.f("ix_events_organization_id"), "events", ["organization_id"], unique=False
    )
    op.create_foreign_key(
        None, "events", "organizations", ["organization_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("incidents", sa.Column("triggering_events", sa.JSON(), nullable=True))
    op.add_column(
        "incidents", sa.Column("events_analyzed_count", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "incidents",
        "ai_analysis_timestamp",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_incidents_organization_id"),
        "incidents",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "incidents",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        "idx_integration_credentials_org_provider", table_name="integration_credentials"
    )
    op.drop_constraint(
        "uq_integration_credentials_org_provider",
        "integration_credentials",
        type_="unique",
    )
    op.create_index(
        op.f("ix_integration_credentials_created_at"),
        "integration_credentials",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_integration_credentials_org_provider",
        "integration_credentials",
        ["organization_id", "provider"],
        unique=True,
    )
    op.create_index(
        op.f("ix_integration_credentials_organization_id"),
        "integration_credentials",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_credentials_provider"),
        "integration_credentials",
        ["provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_credentials_status"),
        "integration_credentials",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_log_sources_organization_id"),
        "log_sources",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "log_sources",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_ml_models_organization_id"),
        "ml_models",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "ml_models",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ml_models", type_="foreignkey")
    op.drop_index(op.f("ix_ml_models_organization_id"), table_name="ml_models")
    op.drop_constraint(None, "log_sources", type_="foreignkey")
    op.drop_index(op.f("ix_log_sources_organization_id"), table_name="log_sources")
    op.drop_index(
        op.f("ix_integration_credentials_status"), table_name="integration_credentials"
    )
    op.drop_index(
        op.f("ix_integration_credentials_provider"),
        table_name="integration_credentials",
    )
    op.drop_index(
        op.f("ix_integration_credentials_organization_id"),
        table_name="integration_credentials",
    )
    op.drop_index(
        "ix_integration_credentials_org_provider", table_name="integration_credentials"
    )
    op.drop_index(
        op.f("ix_integration_credentials_created_at"),
        table_name="integration_credentials",
    )
    op.create_unique_constraint(
        "uq_integration_credentials_org_provider",
        "integration_credentials",
        ["organization_id", "provider"],
    )
    op.create_index(
        "idx_integration_credentials_org_provider",
        "integration_credentials",
        ["organization_id", "provider"],
        unique=False,
    )
    op.drop_constraint(None, "incidents", type_="foreignkey")
    op.drop_index(op.f("ix_incidents_organization_id"), table_name="incidents")
    op.alter_column(
        "incidents",
        "ai_analysis_timestamp",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=True,
    )
    op.drop_column("incidents", "events_analyzed_count")
    op.drop_column("incidents", "triggering_events")
    op.drop_constraint(None, "events", type_="foreignkey")
    op.drop_index(op.f("ix_events_organization_id"), table_name="events")
    op.drop_index("ix_events_org_ts", table_name="events")
    op.drop_constraint(None, "containment_policies", type_="foreignkey")
    op.drop_index(
        op.f("ix_containment_policies_organization_id"),
        table_name="containment_policies",
    )
    op.drop_constraint(None, "cloud_assets", type_="foreignkey")
    op.drop_index(op.f("ix_cloud_assets_provider"), table_name="cloud_assets")
    op.drop_index(op.f("ix_cloud_assets_organization_id"), table_name="cloud_assets")
    op.drop_index("ix_cloud_assets_org_provider_asset", table_name="cloud_assets")
    op.drop_index(op.f("ix_cloud_assets_created_at"), table_name="cloud_assets")
    op.drop_index(op.f("ix_cloud_assets_asset_type"), table_name="cloud_assets")
    op.drop_index(op.f("ix_cloud_assets_asset_id"), table_name="cloud_assets")
    op.drop_index(op.f("ix_cloud_assets_agent_status"), table_name="cloud_assets")
    op.drop_index(op.f("ix_cloud_assets_agent_deployed"), table_name="cloud_assets")
    op.create_unique_constraint(
        "uq_cloud_assets_org_provider_asset",
        "cloud_assets",
        ["organization_id", "provider", "asset_id"],
    )
    op.create_index(
        "idx_cloud_assets_type", "cloud_assets", ["asset_type"], unique=False
    )
    op.create_index(
        "idx_cloud_assets_status", "cloud_assets", ["agent_status"], unique=False
    )
    op.create_index(
        "idx_cloud_assets_org_provider",
        "cloud_assets",
        ["organization_id", "provider"],
        unique=False,
    )
    op.drop_column("cloud_assets", "deployment_error")
    op.drop_column("cloud_assets", "deployment_method")
    op.drop_column("cloud_assets", "agent_enrollment_id")
    op.drop_column("cloud_assets", "created_at")
    op.alter_column(
        "actions",
        "tpot_verification_timestamp",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=True,
    )
    op.drop_constraint(None, "action_logs", type_="foreignkey")
    # ### end Alembic commands ###
