"""add_multi_tenant_support

Revision ID: 8976084bce10
Revises: 04c95f3f8bee
Create Date: 2025-10-09 15:50:09.498725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8976084bce10'
down_revision: Union[str, None] = '04c95f3f8bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create organizations and users tables (new tables, no issue)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_log_sources', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_index(op.f('ix_organizations_status'), 'organizations', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    
    # Add columns to existing tables (use batch mode for SQLite compatibility)
    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_action_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key('fk_action_logs_organization', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.alter_column('tpot_verification_timestamp',
                   existing_type=sa.TIMESTAMP(),
                   type_=sa.DateTime(timezone=True),
                   existing_nullable=True)
    
    with op.batch_alter_table('containment_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_containment_policies_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key('fk_containment_policies_organization', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_events_org_ts', ['organization_id', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key('fk_events_organization', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.alter_column('ai_analysis_timestamp',
                   existing_type=sa.TIMESTAMP(),
                   type_=sa.DateTime(timezone=True),
                   existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_incidents_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key('fk_incidents_organization', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    
    with op.batch_alter_table('log_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_log_sources_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key('fk_log_sources_organization', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ml_models_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key('fk_ml_models_organization', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ml_models_organization', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ml_models_organization_id'))
        batch_op.drop_column('organization_id')
    
    with op.batch_alter_table('log_sources', schema=None) as batch_op:
        batch_op.drop_constraint('fk_log_sources_organization', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_log_sources_organization_id'))
        batch_op.drop_column('organization_id')
    
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_incidents_organization', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_incidents_organization_id'))
        batch_op.alter_column('ai_analysis_timestamp',
                   existing_type=sa.DateTime(timezone=True),
                   type_=sa.TIMESTAMP(),
                   existing_nullable=True)
        batch_op.drop_column('organization_id')
    
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_events_organization', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_events_organization_id'))
        batch_op.drop_index('ix_events_org_ts')
        batch_op.drop_column('organization_id')
    
    with op.batch_alter_table('containment_policies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_containment_policies_organization', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_containment_policies_organization_id'))
        batch_op.drop_column('organization_id')
    
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.alter_column('tpot_verification_timestamp',
                   existing_type=sa.DateTime(timezone=True),
                   type_=sa.TIMESTAMP(),
                   existing_nullable=True)
    
    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_action_logs_organization', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_action_logs_organization_id'))
        batch_op.drop_column('organization_id')
    
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_status'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
