"""Fix AdvancedResponseAction relationship foreign keys

Revision ID: c65b5eaef6b2
Revises: 0502143bdcb1
Create Date: 2025-09-27 22:07:40.758144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c65b5eaef6b2'
down_revision: Union[str, None] = '0502143bdcb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
